### ISSUE TITLE
Using Cortana

### ISSUE THREAD

**Issue by made1990** [akshay2000/XBMCRemoteRT#63]
Hi I saw a video on youtube some of you guys using Cortana to control Kodi which seems to be a great feature:
https://www.youtube.com/watch?v=XYLTCVKFxcI

I tried it using Cortana on Windows Mobile 10 but I did not get it to work. How do I tell cortana to use your app when  I say "Kodi"  ?
Does it matter what language I use for the app and for my phone (cortana) ?

Also what voice commands are there?

[Edit]
Using Lumia 930 - Windows 10 Mobile 14393.693

**Comment by akshay2000** [comment]
You may browse the available commands here: https://github.com/akshay2000/XBMCRemoteRT/blob/master/XBMCRemoteRT/XBMCRemoteRT.WindowsPhone/VCD.xml  

Cortana doesn't work as expected on Windows 10 Mobile because the app was made for Windows Phone 8.1. Cortana works differently in Windows 10 Mobile. I have no plan to upgrade the project to Windows 10 since I have moved on to a [different project](https://github.com/akshay2000/MonocleGiraffe). However, you're welcome to do the upgrade work. I'll be glad to help.
